### ISSUE TITLE
Errors in _getter_Runner.R and _main.R

### ISSUE THREAD

**Issue by mattialopresti** [Aliquanto3/R-Meta-Analysis#1]
By executing the codes, i get some errors in the two named files.

_getter_Runner.R 

```
> #Import raw data 
> RawData = jsonlite::fromJSON(TournamentResultFile)[[1]] 
> tournamentDf = generate_df( +   RawData, EventType, MtgFormat, TournamentResultFile, Beginning, End) 
>  
> ############################   Compute analysis   ##############################  
>  
> # Get the following columns:  
> # Archetype Copies Players Matches Measured.Win.Rate Lower.Bound.of.CI.on.WR Upper.Bound.of.CI.on.WR 
> archetypeMetricsDf = archetype_metrics(tournamentDf) 
     Error in metric_df$Wins + metric_df$Defeats :   non-numeric argument to binary operator 
     Called from: `[.data.frame`(metric_df, metric_df$Wins + metric_df$Defeats >
      0, ) 
Browse[1]>
>
```

_main.R

```
> mtgJsonData = bind_rows(jsonlite::fromJSON(mtgJsonFile)$data, .id = "cardName") 
    Error: lexical error: invalid char in json text.                                        Data/Card/ModernAtomic.json                      
                                                                         (right here) ------^
>
```

Tournament data were compiled as usual using Badaro Tool  with the string:

`MTGOArchetypeParser.App.exe json detect format=Modern filter=modern includedecklists=true exclude=League`

Can you share the last version you are using for the stats please? Thank you very much for your work.

**Comment by Aliquanto3** [comment]
I use several ones depending on my needs, mostly this one when I update all
the formats at once (which is in a directory below the parser, along with a
bunch of other scripts, hence the cd ..):

cd ..

cd MTGODecklistCache
git pull
cd ..

cd MTGOFormatData
git pull
cd ..

MTGOArchetypeParser.App.exe json detect format=Legacy filter=Legacy
includedecklists=true includematchups=true
outputfile=ResultData\Legacy_data.json

MTGOArchetypeParser.App.exe json detect format=Pauper filter=Pauper
includedecklists=true includematchups=true
outputfile=ResultData\Pauper_data.json

MTGOArchetypeParser.App.exe json detect format=Modern filter=Modern
includedecklists=true includematchups=true
outputfile=ResultData\Modern_data.json

MTGOArchetypeParser.App.exe json detect format=Pioneer filter=Pioneer
includedecklists=true includematchups=true
outputfile=ResultData\Pioneer_data.json

MTGOArchetypeParser.App.exe json detect format=Vintage filter=Vintage
includedecklists=true includematchups=true
outputfile=ResultData\Vintage_data.json



Le mer. 3 avr. 2024 à 13:28, mattialopresti ***@***.***> a
écrit :

**Comment by mattialopresti** [comment]
The errors persist even with these lines. 
Do you have an updated version of the R codes to commit?

**Comment by Aliquanto3** [comment]
Indeed, the same code, except that I removed this line as I didn't take
time to implement the feature behind it yet :D

# mtgJsonData = bind_rows(jsonlite::fromJSON(mtgJsonFile)$data, .id =
"cardName")


Le mer. 3 avr. 2024 à 15:09, mattialopresti ***@***.***> a
écrit :

**Comment by mattialopresti** [comment]
Still not working. I'll go for a clean installation of R.

**Comment by mattialopresti** [comment]
I confirm that the problem was with both a previous version of R and an older version of Badaro's software. 
Thank you.

**Comment by Jiliac** [comment]
I guess this issue can be marked as resolved?
